[package]
name = "cargo-apply"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
cargo = "0.10"
walkdir = "0.1"
git2 = "0.4"
libc = "0.2"
docopt = "0.6.80"
rustc-serialize = "0.3.19"
regex = "0.1"
